---

- name: Make Guacamole directory
  become: true
  file:
    path: /etc/guacamole
    state: directory

- name: Download Guacamole Client
  get_url:
    url: https://archive.apache.org/dist/guacamole/1.6.0/binary/guacamole-1.6.0.war
    dest: /tmp/guacamole-1.6.0.war

- name: Move .war
  copy:
    remote_src: True
    src: /tmp/guacamole-1.6.0.war
    dest: /etc/guacamole/guacamole.war

- name: Link guacamole.war to Tomcat webapps
  file:
    src: /etc/guacamole/guacamole.war
    dest: /opt/tomcat/tomcatapp/webapps/guacamole.war
    state: link
